USE master;
GO
ALTER DATABASE QL_SANPHAM 
SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE QL_SANPHAM;

CREATE DATABASE QL_SANPHAM
GO 
USE QL_SANPHAM
GO

CREATE TABLE SANPHAM
(
	MASP CHAR(5) NOT NULL DEFAULT 'SP000',
	TENSP NVARCHAR(50),
	SOLUONG INT,
	DONGIA FLOAT,
	MADM CHAR(5), 
	ISDELETE BIT NOT NULL,
	CONSTRAINT PK_MASP PRIMARY KEY(MASP)
);

CREATE TABLE DANHMUC
(
	MADM CHAR(5) NOT NULL DEFAULT 'DM000',
	TENDM NVARCHAR(50),
	ISDELETE BIT NOT NULL,
	CONSTRAINT PK_MADM PRIMARY KEY(MADM)
);

ALTER TABLE SANPHAM ADD CONSTRAINT FK_MADM FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM);
go

-----------------------------------------------
 CREATE PROC pc_TimMaTiepTheo
    @table VARCHAR(20),
    @id VARCHAR(10) OUT
 AS
 BEGIN
     DECLARE @index INT
     SET @index = 1
     IF @table = 'SANPHAM'
         BEGIN 
         SET @id = 'SP001'
         
         WHILE EXISTS(SELECT MASP FROM SANPHAM WHERE MASP = @id)
         BEGIN
             SET @index = @index + 1
             SET @id = 'SP' + REPLICATE('0',3 - LEN(CAST(@index AS VARCHAR))) + CAST(@index AS VARCHAR)
         END
     END
 
 	ELSE IF @table = 'DANHMUC'
         BEGIN 
         SET @id = 'DM001'
         
         WHILE EXISTS(SELECT MADM FROM DANHMUC WHERE MADM = @id)
         BEGIN
             SET @index = @index + 1
             SET @id = 'DM' + REPLICATE('0',3 - LEN(CAST(@index AS VARCHAR))) + CAST(@index AS VARCHAR)
         END
     END
 
 END
 GO
 ---------------------------------------------------------------------
 CREATE TRIGGER TRG_INSERT_SANPHAM
      ON SANPHAM
      FOR INSERT
 AS
 BEGIN
     --set mã đơn hàng tự động
     PRINT N'MÃ SẼ ĐƯỢC SET TỰ ĐỘNG'
 
     DECLARE @result VARCHAR(10) 
     EXEC pc_TimMaTiepTheo 'SANPHAM', @result OUT
 
     UPDATE SANPHAM
     SET MASP = @result
     FROM SANPHAM JOIN inserted
     ON SANPHAM.MASP = inserted.MASP
 END
 GO

 CREATE TRIGGER TRG_INSERT_DANHMUC
    ON DANHMUC
    FOR INSERT
AS
BEGIN
    --set mã đơn hàng tự động
    PRINT N'MÃ SẼ ĐƯỢC SET TỰ ĐỘNG'

    DECLARE @result VARCHAR(10) 
    EXEC pc_TimMaTiepTheo 'DANHMUC', @result OUT

    UPDATE DANHMUC
    SET MADM = @result
    FROM DANHMUC JOIN inserted
    ON DANHMUC.MADM = inserted.MADM
END
GO

-----------------------------------------------------------------------------

INSERT INTO DANHMUC(TENDM, ISDELETE) VALUES (N'Quần áo', 0)
INSERT INTO DANHMUC(TENDM, ISDELETE) VALUES  (N'Phụ kiện', 0)
INSERT INTO DANHMUC(TENDM, ISDELETE) VALUES  (N'Giày dép', 0)

INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Áo thun', 100, 100000, 'DM001', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Quần jeans', 50, 200000, 'DM002', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Giày thể thao', 20, 300000, 'DM003', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Áo sơ mi', 80, 150000, 'DM001', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Váy đầm', 60, 250000, 'DM001', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Mũ lưỡi trai', 40, 50000, 'DM002', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Kính râm', 30, 120000, 'DM002', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Ví da', 25, 200000, 'DM002', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Túi xách', 20, 350000, 'DM002', 0)
INSERT INTO SANPHAM(TENSP, SOLUONG, DONGIA, MADM, ISDELETE) VALUES (N'Dép lê', 30, 50000, 'DM003', 0)

 SELECT * FROM DANHMUC
 SELECT * FROM SANPHAM